version: "3.7"

services:
  insecureinc:
    image: securecodingdojo/insecure.inc
    build:
      context: ./insecureinc
      dockerfile: Dockerfile.insecureinc
    restart: "always" #change to always if you want the image to auto start
    ports:
      - "8080:8080"
    networks:
      - insecure
    environment:
       - CHALLENGE_MASTER_SALT

  trainingportal:
    image: securecodingdojo/trainingportal
    restart: "always" #change to always if you want the image to auto start
    build:
      context: ./trainingportal
      dockerfile: Dockerfile.trainingportal
    ports:
      - "8081:8081"
    volumes:
       - "/opt/SecureCodingDojo:/dojofiles:consistent"
    networks:
       - portal
    environment:
       - CHALLENGE_MASTER_SALT
       - ENC_KEY
       - ENC_KEY_IV
       - DATA_DIR=/dojofiles

  host1:
    image: securecodingdojo/hackerden-host1
    build:
      context: ./hackerden
      dockerfile: Dockerfile.host1
    restart: "always" 
    expose:
      - "22"
    networks:
      hden:
        aliases:
          - host1

  host2:
    image: securecodingdojo/hackerden-host2
    build:
      context: ./hackerden
      dockerfile: Dockerfile.host2
    restart: "always"
    expose:
      - "8080"
    networks:
      hden:
        aliases:
          - host2

  front:
    image: securecodingdojo/hackerden-front
    build:
      context: ./hackerden
      dockerfile: Dockerfile.front
    restart: "always" 
    ports:
      - "3000:3000"
    environment:
       - CHALLENGE_MASTER_SALT
       - COINMINER_SSH_HOST=host1
       - COMMAND_PROC_URL=http://host2:8080/commandproc
    networks:
      hden:
        aliases:
          - front

volumes:
  dojofiles:

networks:
  portal:
  insecure:
  hden: